{
  loadData="1";
  sleepTime=100;
  throwException.set(new Thrower(){
    public void throwException() throws Exception {
      throw new Exception("exc1");
    }
  }
);
  TTLObject.ObjectException caught=null;
  try {
    assertGetObject("Fetch data first time, throw exception","override",1,0,200000000);
  }
 catch (  TTLObject.ObjectException e) {
    caught=e;
  }
 finally {
    assertNotNull("exception thrown",caught);
    assertEquals("correct exception thrown","exc1",caught.getCause().getMessage());
  }
  caught=null;
  try {
    object.getObject();
  }
 catch (  TTLObject.ObjectException e) {
    caught=e;
  }
 finally {
    assertNotNull("exception thrown",caught);
    assertEquals("correct exception rethrown","exc1",caught.getCause().getMessage());
  }
  Thread.sleep(300);
  loadData="2";
  sleepTime=100;
  assertGetObject("Fetch data after exception, blocked",loadData,2,50000000,200000000);
  loadData="3";
  sleepTime=500;
  throwException.set(new Thrower(){
    public void throwException() throws Exception {
      throw new Exception("exc2");
    }
  }
);
  Thread.sleep(200);
  assertGetObject("Fetch data second time, stale, process pulse","2",2,0,200000000);
  Thread.sleep(600);
  caught=null;
  try {
    assertGetObject("Fetch data second time, throw exception","2",2,0,200000000);
  }
 catch (  TTLObject.ObjectException e) {
    caught=e;
  }
 finally {
    assertNotNull("exception thrown",caught);
    assertEquals("correct exception thrown","exc2",caught.getCause().getMessage());
  }
}
