{
  try {
    assertEquals(label + ": future return",wanted,future.get());
  }
 catch (  InterruptedException e) {
    assertTrue(label + ": expected interruption",interruptable);
  }
catch (  ExecutionException e) {
    assertNotNull(label + ": expecting an exception",thrownClass);
    Throwable caught=e.getCause();
    assertNotNull(label + ": captured exception",caught);
    assertEquals(label + ": correct thrown class",thrownClass,caught.getClass());
    if (thrownMessage != null) {
      assertEquals(label + ": exception message",thrownMessage,caught.getMessage());
    }
  }
}
